import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
/**
 * AMM Work Order Detail — Section 16
 * Cost Proposal Review: read-only WO + invoice table (with warning highlights) + Approve / Request Revision / Close Without Cost.
 */
import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { workOrdersAPI } from '../../api/work-orders';
import { useSession } from '../../contexts/SessionContext';
import { Button, Badge } from '../../components/shared';
import { formatCategory, formatHistoryAction, formatStatus, formatStatusAny } from '../../utils/formatters';
import { WorkOrderStatus } from '../../types/statuses';
export function AMMWorkOrderDetailModal({ workOrderId, onClose, }) {
    const { session } = useSession();
    const queryClient = useQueryClient();
    const [revisionComment, setRevisionComment] = useState('');
    const [showRevisionForm, setShowRevisionForm] = useState(false);
    const [showCloseConfirm, setShowCloseConfirm] = useState(false);
    const [resendComment, setResendComment] = useState('');
    const [showRejectForm, setShowRejectForm] = useState(false);
    const [rejectReason, setRejectReason] = useState('');
    const { data: wo, isLoading } = useQuery({
        queryKey: ['work-order', workOrderId],
        queryFn: () => workOrdersAPI.getById(workOrderId),
        enabled: workOrderId > 0,
    });
    const approveMutation = useMutation({
        mutationFn: () => workOrdersAPI.approveCostProposal(workOrderId),
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['work-orders'] });
            queryClient.invalidateQueries({ queryKey: ['work-order', workOrderId] });
            onClose();
        },
    });
    const revisionMutation = useMutation({
        mutationFn: () => workOrdersAPI.requestCostRevision(workOrderId, revisionComment),
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['work-orders'] });
            queryClient.invalidateQueries({ queryKey: ['work-order', workOrderId] });
            setRevisionComment('');
            setShowRevisionForm(false);
            onClose();
        },
    });
    const closeWithoutCostMutation = useMutation({
        mutationFn: () => workOrdersAPI.closeWithoutCost(workOrderId),
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['work-orders'] });
            queryClient.invalidateQueries({ queryKey: ['work-order', workOrderId] });
            setShowCloseConfirm(false);
            onClose();
        },
    });
    const resendToVendorMutation = useMutation({
        mutationFn: (comment) => workOrdersAPI.resendToVendor(workOrderId, comment || undefined),
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['work-orders'] });
            queryClient.invalidateQueries({ queryKey: ['work-order', workOrderId] });
            setResendComment('');
            onClose();
        },
    });
    const rejectWoMutation = useMutation({
        mutationFn: (reason) => workOrdersAPI.reject(workOrderId, reason),
        onSuccess: () => {
            queryClient.invalidateQueries({ queryKey: ['work-orders'] });
            queryClient.invalidateQueries({ queryKey: ['work-order', workOrderId] });
            setShowRejectForm(false);
            setRejectReason('');
            onClose();
        },
    });
    const isCostProposalPrepared = wo?.currentStatus === WorkOrderStatus.COST_PROPOSAL_PREPARED;
    const isOwner = session?.userId != null && wo?.currentOwnerId === session.userId;
    const canAct = isCostProposalPrepared && isOwner;
    // Returned by S1 to AMM: status Awaiting Service Provider, owner is INTERNAL (AMM)
    const isReturnedToAm = wo?.currentStatus === WorkOrderStatus.CREATED &&
        wo?.currentOwnerType === 'INTERNAL' &&
        isOwner;
    const isAutoGeneratedInvoiceRow = (row) => {
        const desc = row.description.toLowerCase();
        const unit = row.unit.toLowerCase();
        return (desc.includes('arrival') ||
            desc.includes('dolazak') ||
            desc.includes('service time') ||
            desc.includes('service hours') ||
            desc.includes('radni sati') ||
            desc.includes('vrijeme servisa') ||
            unit.includes('15 min'));
    };
    if (isLoading || wo == null) {
        return (_jsx("div", { className: "fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50", children: _jsx("div", { className: "bg-white rounded-lg p-6", children: _jsx("p", { children: "U\u010Ditavanje radnog naloga..." }) }) }));
    }
    return (_jsx("div", { className: "fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50 overflow-y-auto", children: _jsxs("div", { className: "bg-white rounded-lg max-w-4xl w-full my-8", children: [_jsx("div", { className: "p-6 border-b border-gray-200", children: _jsxs("div", { className: "flex justify-between items-start", children: [_jsxs("div", { children: [_jsx("h1", { className: "text-xl font-bold text-gray-900", children: "Detalji radnog naloga" }), _jsxs("p", { className: "text-sm text-gray-600 mt-1", children: ["RN #", wo.id, " \u2022 Prijava #", wo.ticketId] }), _jsx(Badge, { variant: wo.urgent ? 'danger' : 'secondary', className: "mt-2", children: wo.urgent ? 'Hitno' : 'Nije hitno' })] }), _jsx(Button, { type: "button", variant: "secondary", onClick: onClose, children: "Natrag" })] }) }), _jsxs("div", { className: "p-6 space-y-6 max-h-[75vh] overflow-y-auto", children: [_jsxs("section", { children: [_jsx("h2", { className: "font-semibold text-gray-900 mb-2", children: "Detalji" }), _jsxs("div", { className: "bg-gray-50 rounded-lg p-4 space-y-2 text-sm", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-gray-600", children: "Status:" }), _jsx(Badge, { variant: wo.currentStatus === WorkOrderStatus.COST_PROPOSAL_PREPARED ? 'warning' : 'default', children: wo.currentStatus != null ? formatStatus(wo.currentStatus) : '—' })] }), _jsxs("div", { children: [_jsx("span", { className: "text-gray-600", children: "Trenutni vlasnik:" }), ' ', wo.assignedTechnicianName != null && wo.assignedTechnicianName !== ''
                                                    ? wo.assignedTechnicianName
                                                    : wo.currentOwnerType === 'VENDOR'
                                                        ? 'Izvođač (S1)'
                                                        : 'AMM'] }), _jsxs("div", { children: [_jsx("span", { className: "text-gray-600", children: "ETA:" }), ' ', wo.eta != null
                                                    ? new Date(wo.eta).toLocaleString(undefined, { dateStyle: 'short', timeStyle: 'short' })
                                                    : '—'] }), _jsxs("div", { children: [_jsx("span", { className: "text-gray-600", children: "Poslovnica:" }), " ", wo.storeName ?? '—'] }), wo.storeAddress != null && wo.storeAddress !== '' && (_jsxs("div", { children: [_jsx("span", { className: "text-gray-600", children: "Adresa:" }), " ", wo.storeAddress] })), _jsxs("div", { children: [_jsx("span", { className: "text-gray-600", children: "Kategorija:" }), " ", wo.category ? formatCategory(wo.category) : '—'] }), _jsxs("div", { children: [_jsx("span", { className: "text-gray-600", children: "Komentar VMO-a:" }), " ", wo.commentToVendor ?? '—'] }), wo.assetDescription != null && wo.assetDescription !== '' && (_jsxs("div", { children: [_jsx("span", { className: "text-gray-600", children: "Oprema:" }), " ", wo.assetDescription] })), wo.attachments != null && wo.attachments.length > 0 && (_jsxs("div", { children: [_jsx("span", { className: "text-gray-600", children: "Prilozi:" }), _jsx("ul", { className: "list-disc list-inside mt-1", children: wo.attachments.map((a) => (_jsx("li", { children: a.fileName }, a.id))) })] }))] })] }), isReturnedToAm && (_jsxs("section", { className: "space-y-4 border-t pt-4", children: [_jsx("h2", { className: "font-semibold text-gray-900", children: "Akcije (vra\u0107eno od izvo\u0111a\u010Da)" }), _jsx("p", { className: "text-sm text-gray-600", children: "Ovaj radni nalog vra\u0107en je od izvo\u0111a\u010Da (S1). Mo\u017Eete ga ponovno poslati izvo\u0111a\u010Du s neobaveznim komentarom ili ga odbiti." }), _jsxs("div", { className: "grid gap-4 sm:grid-cols-1", children: [_jsxs("div", { className: "bg-blue-50 border border-blue-200 rounded-lg p-4", children: [_jsx("h3", { className: "font-medium text-blue-900 mb-2", children: "Po\u0161alji ponovno izvo\u0111a\u010Du (S1)" }), _jsx("p", { className: "text-sm text-blue-700 mb-3", children: "Vratite radni nalog izvo\u0111a\u010Du. Mo\u017Eete dodati komentar (npr. poja\u0161njenje) za njih." }), _jsx("textarea", { value: resendComment, onChange: (e) => setResendComment(e.target.value), placeholder: "Neobavezan komentar za izvo\u0111a\u010Da...", rows: 2, className: "w-full p-3 border border-gray-300 rounded-lg mb-3" }), _jsx(Button, { type: "button", onClick: () => resendToVendorMutation.mutate(resendComment), disabled: resendToVendorMutation.isPending, children: resendToVendorMutation.isPending ? 'Slanje...' : 'Pošalji ponovno' })] }), _jsxs("div", { className: "bg-red-50 border border-red-200 rounded-lg p-4", children: [_jsx("h3", { className: "font-medium text-red-900 mb-2", children: "Odbij radni nalog" }), !showRejectForm ? (_jsxs(_Fragment, { children: [_jsx("p", { className: "text-sm text-red-700 mb-3", children: "Odbijte ovaj radni nalog. Kona\u010Dno stanje." }), _jsx(Button, { type: "button", variant: "danger", onClick: () => setShowRejectForm(true), children: "Odbij radni nalog" })] })) : (_jsxs("div", { className: "space-y-2", children: [_jsx("label", { className: "block text-sm font-medium text-red-900", children: "Razlog *" }), _jsx("textarea", { value: rejectReason, onChange: (e) => setRejectReason(e.target.value), placeholder: "Razlog odbijanja...", rows: 2, className: "w-full p-3 border border-gray-300 rounded-lg" }), _jsxs("div", { className: "flex gap-2", children: [_jsx(Button, { type: "button", variant: "danger", onClick: () => rejectWoMutation.mutate(rejectReason), disabled: !rejectReason.trim() || rejectWoMutation.isPending, children: rejectWoMutation.isPending ? 'Odbijanje...' : 'Potvrdi odbijanje' }), _jsx(Button, { type: "button", variant: "secondary", onClick: () => {
                                                                        setShowRejectForm(false);
                                                                        setRejectReason('');
                                                                    }, children: "Odustani" })] })] }))] })] }), (resendToVendorMutation.isError || rejectWoMutation.isError) && (_jsx("div", { className: "bg-red-50 border border-red-200 rounded-lg p-3 text-sm text-red-700", children: resendToVendorMutation.error?.response?.data?.error ??
                                        rejectWoMutation.error?.response?.data?.error ??
                                        'Radnja nije uspjela' }))] })), wo.workReport != null && wo.workReport.length > 0 && (_jsxs("section", { children: [_jsx("h2", { className: "font-semibold text-gray-900 mb-2", children: "Izvje\u0161taj tehni\u010Dara (samo pregled)" }), _jsx("div", { className: "overflow-x-auto border border-gray-200 rounded-lg", children: _jsxs("table", { className: "w-full text-sm", children: [_jsx("thead", { children: _jsxs("tr", { className: "bg-gray-100", children: [_jsx("th", { className: "text-left p-2", children: "#" }), _jsx("th", { className: "text-left p-2", children: "Opis" }), _jsx("th", { className: "text-left p-2", children: "Jedinica" }), _jsx("th", { className: "text-right p-2", children: "Koli\u010Dina" })] }) }), _jsx("tbody", { children: wo.workReport.map((row, idx) => (_jsxs("tr", { className: "border-t border-gray-100", children: [_jsx("td", { className: "p-2", children: idx + 1 }), _jsx("td", { className: "p-2", children: row.description }), _jsx("td", { className: "p-2", children: row.unit }), _jsx("td", { className: "p-2 text-right", children: row.quantity })] }, idx))) })] }) })] })), wo.invoiceRows != null && wo.invoiceRows.length > 0 && (_jsxs("section", { children: [_jsx("h2", { className: "font-semibold text-gray-900 mb-2", children: "Ponuda tro\u0161ka (od S3)" }), _jsx("div", { className: "overflow-x-auto border border-gray-200 rounded-lg", children: _jsxs("table", { className: "w-full text-sm", children: [_jsx("thead", { children: _jsxs("tr", { className: "bg-gray-100", children: [_jsx("th", { className: "text-left p-2", children: "#" }), _jsx("th", { className: "text-left p-2", children: "Opis" }), _jsx("th", { className: "text-left p-2", children: "Jedinica" }), _jsx("th", { className: "text-right p-2", children: "Kol." }), _jsx("th", { className: "text-right p-2", children: "Cijena/jed." }), _jsx("th", { className: "text-right p-2", children: "Ukupno" })] }) }), _jsx("tbody", { children: wo.invoiceRows.map((r) => (_jsxs("tr", { className: `border-t border-gray-100 ${r.priceListItemId == null
                                                        ? 'bg-red-50'
                                                        : isAutoGeneratedInvoiceRow(r)
                                                            ? 'bg-yellow-50'
                                                            : 'bg-green-50'}`, children: [_jsx("td", { className: "p-2", children: r.rowNumber }), _jsx("td", { className: "p-2", children: r.description }), _jsx("td", { className: "p-2", children: r.unit }), _jsx("td", { className: "p-2 text-right", children: r.quantity }), _jsxs("td", { className: "p-2 text-right", children: ["\u20AC", Number(r.pricePerUnit).toFixed(2)] }), _jsxs("td", { className: "p-2 text-right", children: ["\u20AC", Number(r.lineTotal).toFixed(2)] })] }, r.id))) })] }) }), wo.totalCost != null && (_jsxs("div", { className: "mt-3 p-3 bg-gray-100 rounded-lg flex justify-between items-center", children: [_jsx("span", { className: "font-semibold text-gray-900", children: "Sveukupno" }), _jsxs("span", { className: "text-lg font-bold", children: ["\u20AC", Number(wo.totalCost).toFixed(2)] })] })), _jsx("p", { className: "text-xs text-gray-600 mt-2", children: "Boje: svijetlo \u017Euta = automatski generirano (vrijeme dolaska/servisa), svijetlo zelena = stavka iz cjenika, svijetlo crvena = stavka izvan cjenika." })] })), canAct && (_jsxs("section", { className: "space-y-4 border-t pt-4", children: [_jsx("h2", { className: "font-semibold text-gray-900", children: "Akcije" }), _jsxs("div", { className: "grid gap-4 sm:grid-cols-1", children: [_jsxs("div", { className: "bg-green-50 border border-green-200 rounded-lg p-4", children: [_jsx("h3", { className: "font-medium text-green-900 mb-2", children: "Odobri ponudu tro\u0161ka" }), _jsx("p", { className: "text-sm text-green-700 mb-3", children: "Finalizirajte ovu ponudu tro\u0161ka. Radni nalog prelazi u odobreno/arhivirano. Prijava se mo\u017Ee arhivirati kad svi radni nalozi budu zatvoreni." }), _jsx(Button, { type: "button", onClick: () => approveMutation.mutate(), disabled: approveMutation.isPending, children: approveMutation.isPending ? 'Odobravanje...' : 'Odobri ponudu troška' })] }), _jsxs("div", { className: "bg-amber-50 border border-amber-200 rounded-lg p-4", children: [_jsx("h3", { className: "font-medium text-amber-900 mb-2", children: "Zatra\u017Ei reviziju ponude" }), !showRevisionForm ? (_jsxs(_Fragment, { children: [_jsx("p", { className: "text-sm text-amber-700 mb-3", children: "Vrati S3 na izmjene. Komentar je obavezan." }), _jsx(Button, { type: "button", variant: "secondary", onClick: () => setShowRevisionForm(true), children: "Zatra\u017Ei reviziju" })] })) : (_jsxs("div", { className: "space-y-2", children: [_jsx("label", { className: "block text-sm font-medium text-amber-900", children: "Komentar *" }), _jsx("textarea", { value: revisionComment, onChange: (e) => setRevisionComment(e.target.value), placeholder: "Objasnite \u0161to treba ispraviti...", rows: 3, className: "w-full p-3 border border-gray-300 rounded-lg" }), _jsxs("div", { className: "flex gap-2", children: [_jsx(Button, { type: "button", onClick: () => revisionMutation.mutate(), disabled: !revisionComment.trim() || revisionMutation.isPending, children: revisionMutation.isPending ? 'Slanje...' : 'Pošalji zahtjev za reviziju' }), _jsx(Button, { type: "button", variant: "secondary", onClick: () => {
                                                                        setShowRevisionForm(false);
                                                                        setRevisionComment('');
                                                                    }, children: "Odustani" })] })] }))] }), _jsxs("div", { className: "bg-gray-100 border border-gray-200 rounded-lg p-4", children: [_jsx("h3", { className: "font-medium text-gray-900 mb-2", children: "Zatvori bez tro\u0161ka" }), !showCloseConfirm ? (_jsxs(_Fragment, { children: [_jsx("p", { className: "text-sm text-gray-700 mb-3", children: "Ra\u010Dun nije potreban (npr. jamstvo, interna odluka). Zavr\u0161no stanje." }), _jsx(Button, { type: "button", variant: "secondary", onClick: () => setShowCloseConfirm(true), children: "Zatvori bez tro\u0161ka" })] })) : (_jsxs("div", { className: "space-y-3", children: [_jsx("p", { className: "text-sm text-gray-700", children: "Jeste li sigurni? Status \u0107e biti Zatvoreno bez tro\u0161ka i radni nalog postaje kona\u010Dan." }), _jsxs("div", { className: "flex gap-2", children: [_jsx(Button, { type: "button", variant: "danger", onClick: () => closeWithoutCostMutation.mutate(), disabled: closeWithoutCostMutation.isPending, children: closeWithoutCostMutation.isPending ? 'Zatvaranje...' : 'Potvrdi zatvaranje bez troška' }), _jsx(Button, { type: "button", variant: "secondary", onClick: () => setShowCloseConfirm(false), children: "Odustani" })] })] }))] })] })] })), wo.auditLog != null && wo.auditLog.length > 0 && (_jsxs("section", { children: [_jsx("h3", { className: "font-semibold text-gray-900 mb-2", children: "Povijest" }), _jsx("div", { className: "space-y-2", children: wo.auditLog.map((entry) => (_jsxs("div", { className: "text-sm bg-gray-50 rounded-lg p-3", children: [_jsx("span", { className: "text-gray-600", children: new Date(entry.createdAt).toLocaleString() }), ' — ', _jsx("span", { className: "font-medium", children: formatHistoryAction(entry.actionType) }), entry.prevStatus != null && (_jsxs("span", { className: "text-gray-600", children: [" (", formatStatusAny(entry.prevStatus), " \u2192 ", formatStatusAny(entry.newStatus), ")"] })), _jsxs("p", { className: "mt-1 text-gray-600", children: ["Izvr\u0161io ", entry.actorName, entry.actorRole != null ? ` (${entry.actorRole})` : ''] }), entry.comment != null && _jsxs("p", { className: "text-gray-600 mt-1", children: ["\"", entry.comment, "\""] })] }, entry.id))) })] })), (approveMutation.isError || revisionMutation.isError || closeWithoutCostMutation.isError) && (_jsx("div", { className: "bg-red-50 border border-red-200 rounded-lg p-4", children: _jsx("p", { className: "text-sm text-red-700", children: approveMutation.error?.response?.data?.error ??
                                    revisionMutation.error?.response?.data?.error ??
                                    closeWithoutCostMutation.error?.response?.data?.error ??
                                    'Radnja nije uspjela' }) }))] })] }) }));
}
