/**
 * AMM Work Order Detail — Section 16
 * Cost Proposal Review: read-only WO + invoice table (with warning highlights) + Approve / Request Revision / Close Without Cost.
 */

import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { workOrdersAPI } from '../../api/work-orders';
import { useSession } from '../../contexts/SessionContext';
import { Button, Badge } from '../../components/shared';
import { formatCategory, formatHistoryAction, formatStatus } from '../../utils/formatters';
import { WorkOrderStatus } from '../../types/statuses';

interface AMMWorkOrderDetailModalProps {
  workOrderId: number;
  onClose: () => void;
}

export function AMMWorkOrderDetailModal({
  workOrderId,
  onClose,
}: AMMWorkOrderDetailModalProps) {
  const { session } = useSession();
  const queryClient = useQueryClient();
  const [revisionComment, setRevisionComment] = useState('');
  const [showRevisionForm, setShowRevisionForm] = useState(false);
  const [showCloseConfirm, setShowCloseConfirm] = useState(false);
  const [resendComment, setResendComment] = useState('');
  const [showRejectForm, setShowRejectForm] = useState(false);
  const [rejectReason, setRejectReason] = useState('');

  const { data: wo, isLoading } = useQuery({
    queryKey: ['work-order', workOrderId],
    queryFn: () => workOrdersAPI.getById(workOrderId),
    enabled: workOrderId > 0,
  });

  const approveMutation = useMutation({
    mutationFn: () => workOrdersAPI.approveCostProposal(workOrderId),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['work-orders'] });
      queryClient.invalidateQueries({ queryKey: ['work-order', workOrderId] });
      onClose();
    },
  });

  const revisionMutation = useMutation({
    mutationFn: () => workOrdersAPI.requestCostRevision(workOrderId, revisionComment),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['work-orders'] });
      queryClient.invalidateQueries({ queryKey: ['work-order', workOrderId] });
      setRevisionComment('');
      setShowRevisionForm(false);
      onClose();
    },
  });

  const closeWithoutCostMutation = useMutation({
    mutationFn: () => workOrdersAPI.closeWithoutCost(workOrderId),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['work-orders'] });
      queryClient.invalidateQueries({ queryKey: ['work-order', workOrderId] });
      setShowCloseConfirm(false);
      onClose();
    },
  });

  const resendToVendorMutation = useMutation({
    mutationFn: (comment: string) => workOrdersAPI.resendToVendor(workOrderId, comment || undefined),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['work-orders'] });
      queryClient.invalidateQueries({ queryKey: ['work-order', workOrderId] });
      setResendComment('');
      onClose();
    },
  });

  const rejectWoMutation = useMutation({
    mutationFn: (reason: string) => workOrdersAPI.reject(workOrderId, reason),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['work-orders'] });
      queryClient.invalidateQueries({ queryKey: ['work-order', workOrderId] });
      setShowRejectForm(false);
      setRejectReason('');
      onClose();
    },
  });

  const isCostProposalPrepared =
    wo?.currentStatus === WorkOrderStatus.COST_PROPOSAL_PREPARED;
  const isOwner = session?.userId != null && wo?.currentOwnerId === session.userId;
  const canAct = isCostProposalPrepared && isOwner;

  // Returned by S1 to AMM: status Awaiting Service Provider, owner is INTERNAL (AMM)
  const isReturnedToAm =
    wo?.currentStatus === WorkOrderStatus.CREATED &&
    wo?.currentOwnerType === 'INTERNAL' &&
    isOwner;

  const isAutoGeneratedInvoiceRow = (row: { description: string; unit: string }): boolean => {
    const desc = row.description.toLowerCase();
    const unit = row.unit.toLowerCase();
    return (
      desc.includes('arrival') ||
      desc.includes('dolazak') ||
      desc.includes('service time') ||
      desc.includes('service hours') ||
      desc.includes('radni sati') ||
      desc.includes('vrijeme servisa') ||
      unit.includes('15 min')
    );
  };

  if (isLoading || wo == null) {
    return (
      <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
        <div className="bg-white rounded-lg p-6">
          <p>Učitavanje radnog naloga...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50 overflow-y-auto">
      <div className="bg-white rounded-lg max-w-4xl w-full my-8">
        <div className="p-6 border-b border-gray-200">
          <div className="flex justify-between items-start">
            <div>
              <h1 className="text-xl font-bold text-gray-900">Detalji radnog naloga</h1>
              <p className="text-sm text-gray-600 mt-1">
                RN #{wo.id} • Prijava #{wo.ticketId}
              </p>
              <Badge variant={wo.urgent ? 'danger' : 'secondary'} className="mt-2">
                {wo.urgent ? 'Hitno' : 'Nije hitno'}
              </Badge>
            </div>
            <Button type="button" variant="secondary" onClick={onClose}>
              Natrag
            </Button>
          </div>
        </div>

        <div className="p-6 space-y-6 max-h-[75vh] overflow-y-auto">
          {/* 16.2 Read-only sections */}
          <section>
            <h2 className="font-semibold text-gray-900 mb-2">Detalji</h2>
            <div className="bg-gray-50 rounded-lg p-4 space-y-2 text-sm">
              <div className="flex items-center gap-2">
                <span className="text-gray-600">Status:</span>
                <Badge variant={wo.currentStatus === WorkOrderStatus.COST_PROPOSAL_PREPARED ? 'warning' : 'default'}>
                  {wo.currentStatus != null ? formatStatus(wo.currentStatus) : '—'}
                </Badge>
              </div>
              <div>
                <span className="text-gray-600">Trenutni vlasnik:</span>{' '}
                {wo.assignedTechnicianName != null && wo.assignedTechnicianName !== ''
                  ? wo.assignedTechnicianName
                  : wo.currentOwnerType === 'VENDOR'
                    ? 'Izvođač (S1)'
                    : 'AMM'}
              </div>
              <div>
                <span className="text-gray-600">ETA:</span>{' '}
                {wo.eta != null
                  ? new Date(wo.eta).toLocaleString(undefined, { dateStyle: 'short', timeStyle: 'short' })
                  : '—'}
              </div>
              <div><span className="text-gray-600">Poslovnica:</span> {wo.storeName ?? '—'}</div>
              {wo.storeAddress != null && wo.storeAddress !== '' && (
                <div><span className="text-gray-600">Adresa:</span> {wo.storeAddress}</div>
              )}
              <div><span className="text-gray-600">Kategorija:</span> {wo.category ? formatCategory(wo.category) : '—'}</div>
              <div><span className="text-gray-600">Komentar VMO-a:</span> {wo.commentToVendor ?? '—'}</div>
              {wo.assetDescription != null && wo.assetDescription !== '' && (
                <div><span className="text-gray-600">Oprema:</span> {wo.assetDescription}</div>
              )}
              {wo.attachments != null && wo.attachments.length > 0 && (
                <div>
                  <span className="text-gray-600">Prilozi:</span>
                  <ul className="list-disc list-inside mt-1">
                    {wo.attachments.map((a) => (
                      <li key={a.id}>{a.fileName}</li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          </section>

          {/* Returned by S1: AMM can resend to vendor or reject */}
          {isReturnedToAm && (
            <section className="space-y-4 border-t pt-4">
              <h2 className="font-semibold text-gray-900">Akcije (vraćeno od izvođača)</h2>
              <p className="text-sm text-gray-600">
                Ovaj radni nalog vraćen je od izvođača (S1). Možete ga ponovno poslati izvođaču s neobaveznim komentarom ili ga odbiti.
              </p>
              <div className="grid gap-4 sm:grid-cols-1">
                <div className="bg-blue-50 border border-blue-200 rounded-lg p-4">
                  <h3 className="font-medium text-blue-900 mb-2">Pošalji ponovno izvođaču (S1)</h3>
                  <p className="text-sm text-blue-700 mb-3">
                    Vratite radni nalog izvođaču. Možete dodati komentar (npr. pojašnjenje) za njih.
                  </p>
                  <textarea
                    value={resendComment}
                    onChange={(e) => setResendComment(e.target.value)}
                    placeholder="Neobavezan komentar za izvođača..."
                    rows={2}
                    className="w-full p-3 border border-gray-300 rounded-lg mb-3"
                  />
                  <Button
                    type="button"
                    onClick={() => resendToVendorMutation.mutate(resendComment)}
                    disabled={resendToVendorMutation.isPending}
                  >
                    {resendToVendorMutation.isPending ? 'Slanje...' : 'Pošalji ponovno'}
                  </Button>
                </div>
                <div className="bg-red-50 border border-red-200 rounded-lg p-4">
                  <h3 className="font-medium text-red-900 mb-2">Odbij radni nalog</h3>
                  {!showRejectForm ? (
                    <>
                      <p className="text-sm text-red-700 mb-3">
                        Odbijte ovaj radni nalog. Konačno stanje.
                      </p>
                      <Button
                        type="button"
                        variant="danger"
                        onClick={() => setShowRejectForm(true)}
                      >
                        Odbij radni nalog
                      </Button>
                    </>
                  ) : (
                    <div className="space-y-2">
                      <label className="block text-sm font-medium text-red-900">Razlog *</label>
                      <textarea
                        value={rejectReason}
                        onChange={(e) => setRejectReason(e.target.value)}
                        placeholder="Razlog odbijanja..."
                        rows={2}
                        className="w-full p-3 border border-gray-300 rounded-lg"
                      />
                      <div className="flex gap-2">
                        <Button
                          type="button"
                          variant="danger"
                          onClick={() => rejectWoMutation.mutate(rejectReason)}
                          disabled={!rejectReason.trim() || rejectWoMutation.isPending}
                        >
                          {rejectWoMutation.isPending ? 'Odbijanje...' : 'Potvrdi odbijanje'}
                        </Button>
                        <Button
                          type="button"
                          variant="secondary"
                          onClick={() => {
                            setShowRejectForm(false);
                            setRejectReason('');
                          }}
                        >
                          Odustani
                        </Button>
                      </div>
                    </div>
                  )}
                </div>
              </div>
              {(resendToVendorMutation.isError || rejectWoMutation.isError) && (
                <div className="bg-red-50 border border-red-200 rounded-lg p-3 text-sm text-red-700">
                  {(resendToVendorMutation.error as { response?: { data?: { error?: string } } })?.response?.data?.error ??
                    (rejectWoMutation.error as { response?: { data?: { error?: string } } })?.response?.data?.error ??
                    'Radnja nije uspjela'}
                </div>
              )}
            </section>
          )}

          {wo.workReport != null && wo.workReport.length > 0 && (
            <section>
              <h2 className="font-semibold text-gray-900 mb-2">Izvještaj tehničara (samo pregled)</h2>
              <div className="overflow-x-auto border border-gray-200 rounded-lg">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="bg-gray-100">
                      <th className="text-left p-2">#</th>
                      <th className="text-left p-2">Opis</th>
                      <th className="text-left p-2">Jedinica</th>
                      <th className="text-right p-2">Količina</th>
                    </tr>
                  </thead>
                  <tbody>
                    {wo.workReport.map((row, idx) => (
                      <tr key={idx} className="border-t border-gray-100">
                        <td className="p-2">{idx + 1}</td>
                        <td className="p-2">{row.description}</td>
                        <td className="p-2">{row.unit}</td>
                        <td className="p-2 text-right">{row.quantity}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </section>
          )}

          {/* 16.3 Invoice proposal table (read-only, highlighted rows if warning) */}
          {wo.invoiceRows != null && wo.invoiceRows.length > 0 && (
            <section>
              <h2 className="font-semibold text-gray-900 mb-2">Ponuda troška (od S3)</h2>
              <div className="overflow-x-auto border border-gray-200 rounded-lg">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="bg-gray-100">
                      <th className="text-left p-2">#</th>
                      <th className="text-left p-2">Opis</th>
                      <th className="text-left p-2">Jedinica</th>
                      <th className="text-right p-2">Kol.</th>
                      <th className="text-right p-2">Cijena/jed.</th>
                      <th className="text-right p-2">Ukupno</th>
                    </tr>
                  </thead>
                  <tbody>
                    {wo.invoiceRows.map((r) => (
                      <tr
                        key={r.id}
                        className={`border-t border-gray-100 ${
                          r.priceListItemId == null
                            ? 'bg-red-50'
                            : isAutoGeneratedInvoiceRow(r)
                              ? 'bg-yellow-50'
                              : 'bg-green-50'
                        }`}
                      >
                        <td className="p-2">{r.rowNumber}</td>
                        <td className="p-2">{r.description}</td>
                        <td className="p-2">{r.unit}</td>
                        <td className="p-2 text-right">{r.quantity}</td>
                        <td className="p-2 text-right">€{Number(r.pricePerUnit).toFixed(2)}</td>
                        <td className="p-2 text-right">€{Number(r.lineTotal).toFixed(2)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              {wo.totalCost != null && (
                <div className="mt-3 p-3 bg-gray-100 rounded-lg flex justify-between items-center">
                  <span className="font-semibold text-gray-900">Sveukupno</span>
                  <span className="text-lg font-bold">€{Number(wo.totalCost).toFixed(2)}</span>
                </div>
              )}
              <p className="text-xs text-gray-600 mt-2">
                Boje: svijetlo žuta = automatski generirano (vrijeme dolaska/servisa), svijetlo zelena = stavka iz cjenika, svijetlo crvena = stavka izvan cjenika.
              </p>
            </section>
          )}

          {/* 16.4–16.7 AMM action buttons */}
          {canAct && (
            <section className="space-y-4 border-t pt-4">
              <h2 className="font-semibold text-gray-900">Akcije</h2>
              <div className="grid gap-4 sm:grid-cols-1">
                <div className="bg-green-50 border border-green-200 rounded-lg p-4">
                  <h3 className="font-medium text-green-900 mb-2">Odobri ponudu troška</h3>
                  <p className="text-sm text-green-700 mb-3">
                    Finalizirajte ovu ponudu troška. Radni nalog prelazi u odobreno/arhivirano. Prijava se može arhivirati kad svi radni nalozi budu zatvoreni.
                  </p>
                  <Button
                    type="button"
                    onClick={() => approveMutation.mutate()}
                    disabled={approveMutation.isPending}
                  >
                    {approveMutation.isPending ? 'Odobravanje...' : 'Odobri ponudu troška'}
                  </Button>
                </div>

                <div className="bg-amber-50 border border-amber-200 rounded-lg p-4">
                  <h3 className="font-medium text-amber-900 mb-2">Zatraži reviziju ponude</h3>
                  {!showRevisionForm ? (
                    <>
                      <p className="text-sm text-amber-700 mb-3">
                        Vrati S3 na izmjene. Komentar je obavezan.
                      </p>
                      <Button
                        type="button"
                        variant="secondary"
                        onClick={() => setShowRevisionForm(true)}
                      >
                        Zatraži reviziju
                      </Button>
                    </>
                  ) : (
                    <div className="space-y-2">
                      <label className="block text-sm font-medium text-amber-900">Komentar *</label>
                      <textarea
                        value={revisionComment}
                        onChange={(e) => setRevisionComment(e.target.value)}
                        placeholder="Objasnite što treba ispraviti..."
                        rows={3}
                        className="w-full p-3 border border-gray-300 rounded-lg"
                      />
                      <div className="flex gap-2">
                        <Button
                          type="button"
                          onClick={() => revisionMutation.mutate()}
                          disabled={!revisionComment.trim() || revisionMutation.isPending}
                        >
                          {revisionMutation.isPending ? 'Slanje...' : 'Pošalji zahtjev za reviziju'}
                        </Button>
                        <Button
                          type="button"
                          variant="secondary"
                          onClick={() => {
                            setShowRevisionForm(false);
                            setRevisionComment('');
                          }}
                        >
                          Odustani
                        </Button>
                      </div>
                    </div>
                  )}
                </div>

                <div className="bg-gray-100 border border-gray-200 rounded-lg p-4">
                  <h3 className="font-medium text-gray-900 mb-2">Zatvori bez troška</h3>
                  {!showCloseConfirm ? (
                    <>
                      <p className="text-sm text-gray-700 mb-3">
                        Račun nije potreban (npr. jamstvo, interna odluka). Završno stanje.
                      </p>
                      <Button
                        type="button"
                        variant="secondary"
                        onClick={() => setShowCloseConfirm(true)}
                      >
                        Zatvori bez troška
                      </Button>
                    </>
                  ) : (
                    <div className="space-y-3">
                      <p className="text-sm text-gray-700">
                        Jeste li sigurni? Status će biti Zatvoreno bez troška i radni nalog postaje konačan.
                      </p>
                      <div className="flex gap-2">
                        <Button
                          type="button"
                          variant="danger"
                          onClick={() => closeWithoutCostMutation.mutate()}
                          disabled={closeWithoutCostMutation.isPending}
                        >
                          {closeWithoutCostMutation.isPending ? 'Zatvaranje...' : 'Potvrdi zatvaranje bez troška'}
                        </Button>
                        <Button
                          type="button"
                          variant="secondary"
                          onClick={() => setShowCloseConfirm(false)}
                        >
                          Odustani
                        </Button>
                      </div>
                    </div>
                  )}
                </div>
              </div>
            </section>
          )}

          {/* History — actions with comments, newest first */}
          {wo.auditLog != null && wo.auditLog.length > 0 && (
            <section>
              <h3 className="font-semibold text-gray-900 mb-2">Povijest</h3>
              <div className="space-y-2">
                {wo.auditLog.map((entry) => (
                  <div key={entry.id} className="text-sm bg-gray-50 rounded-lg p-3">
                    <span className="text-gray-600">{new Date(entry.createdAt).toLocaleString()}</span>
                    {' — '}
                    <span className="font-medium">{formatHistoryAction(entry.actionType)}</span>
                    {entry.prevStatus != null && (
                      <span className="text-gray-600"> ({entry.prevStatus} → {entry.newStatus})</span>
                    )}
                    <p className="mt-1 text-gray-600">
                      Izvršio {entry.actorName}{entry.actorRole != null ? ` (${entry.actorRole})` : ''}
                    </p>
                    {entry.comment != null && <p className="text-gray-600 mt-1">&quot;{entry.comment}&quot;</p>}
                  </div>
                ))}
              </div>
            </section>
          )}

          {(approveMutation.isError || revisionMutation.isError || closeWithoutCostMutation.isError) && (
            <div className="bg-red-50 border border-red-200 rounded-lg p-4">
              <p className="text-sm text-red-700">
                {(approveMutation.error as { response?: { data?: { error?: string } } })?.response?.data?.error ??
                  (revisionMutation.error as { response?: { data?: { error?: string } } })?.response?.data?.error ??
                  (closeWithoutCostMutation.error as { response?: { data?: { error?: string } } })?.response?.data?.error ??
                  'Radnja nije uspjela'}
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
